svh/api/urls.py
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import url

svh/svh/urls.py
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view
from rest_framework import routers

from api.views import VideoFolderViewSet
from svh.views.videos import index, play_video, page_from, page_by_type
from svh.views.api import update_library_cmd, is_superuser
from svh.views.admin import regex_rename_sources, regex_ajax

schema_view = get_swagger_view(title='SVH API')
router = routers.DefaultRouter()
router.register(r'videofolders', VideoFolderViewSet)

urlpatterns = [url(r'^admin/', admin.site.urls), url(r'^$', index),
               url(r'^videos/(\d+)/$', play_video, name='play_video'), url(r'(\d+)/$', page_from, name='page'),
               url(r'^types/([\w\-]+)/$', page_by_type, name='by_type'),
               url(r'^updatelibrary/$', update_library_cmd, name='update_library'),
               url(r'^superuser/$', is_superuser, name='superuser'),
               url(r'^admin/rename', regex_rename_sources, name='rename'),
               url(r'^admin/regex', regex_ajax, name='regex'),
               url(r'^api/', schema_view),
               path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
               path('', include(router.urls)),
               ]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svh/svh/models.py
from django.conf import settings
from django.db import models
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
import os
from svh.fileservice.proxy import get_file_url, start_conversion

BIRTH_PLACES = ('user', 'torrent', 'upload')


class VideoFolderManager(models.Manager):
    def all_types(self):
        return self.exclude(type=None).order_by().values_list('type', flat=True).distinct()

    def get_queryset(self):
        return super(VideoFolderManager, self).get_queryset().exclude(deleted=True)

    def all_with_deleted(self, **kwargs):
        return super(VideoFolderManager, self).get_queryset().all()

    def get_or_create_with_hierarchy(self, folderPath, save=True):
        folder = self.get_queryset().filter(path=folderPath).first()
        if folder is None:
            folder = VideoFolder(path=folderPath)
            if folderPath is not '':
                parent_path = os.path.dirname(folderPath)
                parent = self.get_or_create_with_hierarchy(parent_path)
                parent.save()
                folder.parent=parent
            folder.save()

        return folder


class VideoFolder(MPTTModel):
    class Meta:
        ordering = ('path',)
    _name = models.CharField(max_length=500, null=True, db_column='name', blank=True)
    path = models.CharField(max_length=2000, unique=True)
    type = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    parent = TreeForeignKey('self',
                            related_name='folder_parent',
                            null=True, on_delete=models.DO_NOTHING, blank=True)
    deleted = models.BooleanField(default=False)
    objects = VideoFolderManager()
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def name(self):
        if self._name == None:
            return os.path.splitext(self.path)[0].replace(settings.SOURCE_VIDEOS_PATH,'')
        return self._name

    @property
    def first_video(self):
        return self.videosource_set.first()

    @property
    def preview(self):
        sources = self.videosource_set.exclude(preview=None)
        if not sources.exists():
            sources = VideoSource.objects.filter(folder__in=self.get_descendants()).exclude(preview=None)
        return sources.first().preview if sources.exists() else None


class VideoSourceManager(models.Manager):
    def get_queryset(self):
        return super(VideoSourceManager, self).get_queryset().exclude(deleted=True)

    def get_with_deleted(self, **kwargs):
        return super(VideoSourceManager, self).get_queryset().get(**kwargs)

    def all_with_deleted(self, **kwargs):
        return super(VideoSourceManager, self).get_queryset().all()


class VideoSource(models.Model):
    _name = models.CharField(max_length=500, null=True, db_column='name')
    path = models.CharField(max_length=2000,  unique=True)
    hash = models.CharField(max_length=200, unique=True)
    sizeBytes = models.IntegerField(null=True)
    deleted = models.BooleanField(default=False)
    folder = models.ForeignKey(VideoFolder,on_delete=models.SET_NULL, null=True)
    objects = VideoSourceManager()
    published = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def name(self):
        if self._name == None:
            return os.path.splitext(os.path.basename(self.path))[0]
        return self._name

    @property
    def videofile(self):
        if settings.ALLOW_SOURCE_SERVING and not self.videofile_set.exists():
            vf = VideoFile(format='default', source=self, fileId=self.hash)
            return vf
        return self.videofile_set.first()

    @property
    def preview(self):
        preview = self.preview_set.first()
        return preview or start_conversion(self.hash, 'preview')

    @property
    def gif_url(self):
        if hasattr(self, 'gif'):
            return self.gif.url
        else:
            start_conversion(self.hash, 'gif')
            if self.preview:
                return self.preview.url
            else:
                return None  # todo if no preview - return default img


class VideoFile(models.Model):
    fileId = models.CharField(max_length=2000, unique=True)
    format = models.CharField(max_length=200)
    source = models.ForeignKey(VideoSource, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.source.path + self.format

    @property
    def url(self):
        return get_file_url(self.fileId)


class Preview(models.Model): # todo delete file on model deletion
    videosource = models.ForeignKey(VideoSource, on_delete=models.CASCADE)
    fileId = models.CharField(max_length=2000, unique=False)

    @property
    def url(self):
        return get_file_url(self.fileId)


class Gif(models.Model): # todo delete file on model deletion
    videosource = models.OneToOneField(VideoSource, on_delete=models.CASCADE)
    fileId = models.CharField(max_length=2000, unique=True)

    @property
    def url(self):
        return get_file_url(self.fileId)

svh/svh/forms.py
from django import forms


class AddFolderForm(forms.Form):
    magnet = forms.CharField()


class RenameForm(forms.Form):
    find = forms.CharField(max_length=100)
    replace = forms.CharField(required=False, max_length=100)
    ids = forms.CharField(widget=forms.HiddenInput())

svh/svh/views/admin.py
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
import re

from svh.forms import RenameForm
from svh.models import VideoSource


@staff_member_required
def regex_rename_sources(request):
    ids = request.GET.get('ids') or request.POST.get('ids')
    if not ids:
        return HttpResponseBadRequest()
    vs_list = [get_object_or_404(VideoSource, id=i) for i in ids.split(',')]

    if request.method == 'POST':
        form = RenameForm(request.POST)
        if form.is_valid():
            for vs in vs_list:
                vs._name = _regex(vs.name, form.cleaned_data.get('find'), form.cleaned_data.get('replace'))
                vs.save()
            form = RenameForm({'ids': ids})
    else:
        form = RenameForm(request.GET)

    context = {
        'vs_list': vs_list,
        'form': form
    }
    return render(request, 'svh/rename.html', context)


@staff_member_required
def regex_ajax(request):
    result = _regex(request.GET.get('str'), request.GET.get('find'), request.GET.get('replace'))
    return HttpResponse(result)


def _regex(str, find, replace):
    try:
        return re.sub(find or '', replace or '', str)
    except:
        return ''

svh/svh/views/api.py
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from qbittorrentapi import Client
from svh.tasks import update_library
from svh import settings


def torrent_finished(request, torrent_hash):
    client = Client(host=settings.TORRENT_SERVICE_URL, username='admin', password='adminadmin')
    client.torrents_delete(False,[torrent_hash])
    update_library.delay()
    return HttpResponse()


@csrf_exempt
def is_superuser(request):
    if request.user.is_staff:
        return HttpResponse()
    else:
        return HttpResponseForbidden()


@staff_member_required
def update_library_cmd(request):
    update_library().delay()
    return HttpResponse("OK")

svh/svh/views/videos.py
from django.shortcuts import render, get_object_or_404, get_list_or_404

from svh.forms import AddFolderForm
from svh.models import VideoFolder, VideoSource
from svh.tasks import download_torrent, update_library


def index(request):
    root = VideoFolder.objects.filter(level=0).first()
    if not root:
        return render(request, 'svh/index.html')
    return page_from(request, root.pk)


def page_from(request, root):
    root_folder = get_object_or_404(VideoFolder, pk=root)

    if request.method == "POST":
        add_folder_form = AddFolderForm(request.POST)  # todo validation
        if add_folder_form.is_valid():
            download_torrent(add_folder_form['magnet'].value(), root_folder.path)
    else:
        add_folder_form = AddFolderForm()

    children = root_folder.get_children()

    videos = root_folder.videosource_set.order_by()

    if not request.user.is_staff:
        children = children.filter(published=True).order_by('_name')
        videos = videos.filter(published=True).order_by('_name')

    return render(request, 'svh/index.html', {
        'parent': root_folder.parent,
        'folders': children,
        'videosources': videos,
        'add_folder_form': add_folder_form
    })  # todo preview - from description.yaml or random video + for videos


def play_video(request, id, format='default'):
    videosource = get_object_or_404(VideoSource, id=id)
    neighbours = VideoSource.objects.filter(folder=videosource.folder)
    return render(request, 'svh/videoplayer.html', {
        'videosource': videosource,
        'videosources_near': neighbours,
    })


def page_by_type(request, type):
    folders = VideoFolder.objects.filter(type=type)
    return render(request, 'svh/index.html', {
        'folders': folders,
    })

svh/svh/templates/svh/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
    <title>Simple Video hosting site</title>
    <link rel="stylesheet" href="{% static "style.css" %}"/>
    <script src="{% static "scripts.js" %}"></script>
    {{ metrika | safe }}
</head>
<body>
<div class="jumbotron text-center" style="margin-bottom:0">
    <h1><a href="/">Simple Video Hosting</a></h1>
</div>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="#">Top categories:</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            {% for t in types %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'by_type' t %}">{{ t }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-2">
            {% block navigation %}{% endblock %}
        </div>
        <div class="col-10">
            {% block content %}{% endblock %}
        </div>
    </div>
    {% if user.is_staff %}
        <div class="row">
            <form id="updateLibraryForm">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Update Library</button>
            </form>
        </div>
    {% endif %}
</div>

<div class="jumbotron text-center" style="margin-bottom:0">
    <p>Powered by djbios</p>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src='https://vjs.zencdn.net/7.5.4/video.js'></script>
<script>
  $(document).ready(function () {
        $('#updateLibraryForm').submit(function () {
            $.ajax({
                type: "POST",
                url: {% url 'update_library' %},
            });
            return false;
        });
    });
</script>
</body>
</html>

svh/svh/templates/svh/index.html
{% extends "svh/base.html" %}
{% block navigation %}

{% endblock %}
{% block content %}
    <script>
        var sourceSwap = function () {
            var $this = $(this);
            var newSource = $this.data('alt-src');
            $this.data('alt-src', $this.attr('src'));
            $this.attr('src', newSource);
        };

        $(function () {
            $('img.with-gif').hover(sourceSwap, sourceSwap);
        });
    </script>


    {% if parent %}
        <h4><a href="{% url 'page' parent.id %}">{{ parent.name }}</a></h4>
    {% endif %}

{% if user.is_staff %}
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Download
                    torrent here
                </button>
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <form method="POST" >
                                {% csrf_token %}
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Download torrent</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {{ add_folder_form.as_p }}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            {% endif %}

    {% if folders %}
        <div>
            {% for folder in folders %}
                {% if forloop.first %}
                    <div class="row">{% endif %}
            <div class="col-xs-4">
                <a class="card-with-href" href="{% url 'page' folder.id %}">
                    <div class="card" style="width: 18rem;">
                        <img alt="{{ folder.name }}" class="with-gif card-img-top"
                             src="{{ folder.preview.url }}"/> <br/>
                        <div class="card-body">
                            <h5 class="card-title">{{ folder.name }}</h5>
                            <p class="card-text">{{ folder.description }}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% if forloop.counter|divisibleby:3 %}</div>
                <div class="row">{% endif %}
            {% if forloop.last %}</div>{% endif %}
            {% endfor %}
        </div>
    {% endif %}


    {% if videosources %}
        <h5>Videos:</h5>
        <ul class="list-group">
            {% for video in videosources %}
                <li class="list-group-item {% if not video.published %}disabled-li{% endif %}">
                    <img alt="{{ video.name }}" class="with-gif" data-alt-src="{{ video.gif_url }}"
                         src="{{ video.preview.url }}"/> <br/>
                    <a href="{% url 'play_video' video.id %}">{{ video.name }}</a><br>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

svh/svh/templates/svh/rename.html
{% extends "svh/base.html" %}
{% block navigation %}

{% endblock %}
{% block content %}
    <form method="post" action='{% url 'rename' %}'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Rename"/>
    </form>

    {% for vs in vs_list %}
        <div class="namePair">
            <label class="oldName">{{ vs.name }}</label> - <label class="newName"></label> <br>
        </div>

    {% endfor %}

    <script>
        let update_func = function(){
              $( ".namePair" ).each(function( index ) {
                    let oldname = $(this).children('.oldName');
                    let newname = $(this).children('.newName');
                    $.ajax({
                            method: "GET",
                            url:  '{% url 'regex' %}?str='+oldname.text()+'&&find='+$('#id_find').val()+'&&replace='+$('#id_replace').val(),
                            success: function (data, textStatus) {
                                newname.html(data)
                            }
                        });
                    });
        };

        $(document).ready(function () {
            $('#id_find').on('input', function () {
                update_func();
            });
        });

        $(document).ready(function () {
            $('#id_replace').on('input', function () {
                update_func();
            });
        });
        update_func();
    </script>

{% endblock %}

svh/svh/templates/svh/videoplayer.html
{% extends "svh/base.html" %}
{% block navigation %}
    <h5>Parent <a href="{% url 'page' videosource.folder.id %}">{{ videosource.name }} </a><br></h5>
    <h5>Neighbours:</h5>
    <div>
        {% for video in videosources_near %}
            <a href="{% url 'play_video' video.id %}">{{ video.name }} </a><br>
        {% endfor %}
    </div>
{% endblock %}

{% block content %}

    <video id='my-video' class='video-js' controls preload='auto' width='640' height='264'
           poster='{{ videosource.videofile.one_preview.image.url }}' data-setup='{}'>

        <source src="{{ videosource.videofile.url }}" type='video/mp4'>
        <p class='vjs-no-js'>
            To view this video please enable JavaScript, and consider upgrading to a web browser that
            <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
        </p>
    </video>
{% endblock %}